function synthesizeReport({
  seed,
  lifeGraph,
  eventSedimentation,
  materialQuality,
  agents,
  externalAgents,
  conflicts,
  stage,
  lifeEvents,
  couplings,
  advancedCouplings,
  symbolicSignals,
  symbolicCouplings,
  familySystemMatches,
  educationPathMatches,
  intergenerationalFamilyMatches,
  placeMobilityMatches,
  peerAuthorityMatches,
  classMoneyShameMatches,
  bodyRhythmDigitalMatches,
  meaningBeliefMatches,
  romanticHistoryMatches,
  worldviewOrientationMatches,
  agencyControlMatches,
  timeFutureOrientationMatches,
  relationshipPatternMatches,
  assetMobilityMatches,
  environmentPatternMatches,
  lifeTimelineMatches,
  valueSystemMatches,
  decisionStyleMatches,
  socialCapitalMatches,
  energyDepletionMatches,
  intimacyFamilyPathMatches,
  wealthPathMatches,
  moneyPersonalityMatches,
  savingBehaviorMatches,
  healthFinancialMatches,
  familyFinanceMatches,
  incomePathMatches,
  macroEraMatches,
  turningPoints,
  branchWeights,
  branches,
  lifeEvolution,
  deepSimulation,
  llmSimulationCost,
  llmReactionPlan,
  calibration,
  confidenceExplanation,
  reviewPath,
  world,
  worldForces
}) {
  const names = agents.map((agent) => agent.name).join(", ");
  const mainConflict = conflicts[0];

  return {
    title: "FormSight Parallel Life Simulation Report",
    current_question: seed.profile?.current_question,
    life_stage: stage.name,
    life_graph: lifeGraph,
    event_sedimentation: eventSedimentation,
    material_quality: materialQuality,
    dominant_agents: agents.map((agent) => ({
      id: agent.id,
      name: agent.name,
      desire: agent.desire,
      fear: agent.fear,
      strategy: agent.strategy,
      life_pull: agent.life_pull,
      score: agent.score
    })),
    external_agents: externalAgents.map((agent) => ({
      id: agent.id,
      name: agent.name,
      domain: agent.domain,
      pressure_style: agent.pressure_style,
      life_effect: agent.life_effect,
      score: agent.score
    })),
    core_conflict: {
      id: mainConflict.id,
      name: mainConflict.name,
      dynamic: mainConflict.dynamic,
      risk: mainConflict.trajectory_risk
    },
    summary: `This simulation identifies ${names} as the dominant inner agents. The central pattern is "${mainConflict.name}". At the ${stage.name} stage, this pattern interacts with pressure fields such as ${stage.pressure_fields.join(", ")}.`,
    stage,
    life_events: lifeEvents,
    couplings,
    advanced_couplings: advancedCouplings,
    symbolic_signals: symbolicSignals,
    symbolic_couplings: symbolicCouplings,
    family_system_matches: familySystemMatches,
    education_path_matches: educationPathMatches,
    intergenerational_family_matches: intergenerationalFamilyMatches,
    place_mobility_matches: placeMobilityMatches,
    peer_authority_matches: peerAuthorityMatches,
    class_money_shame_matches: classMoneyShameMatches,
    body_rhythm_digital_matches: bodyRhythmDigitalMatches,
    meaning_belief_matches: meaningBeliefMatches,
    romantic_history_matches: romanticHistoryMatches,
    worldview_orientation_matches: worldviewOrientationMatches,
    agency_control_matches: agencyControlMatches,
    time_future_orientation_matches: timeFutureOrientationMatches,
    relationship_pattern_matches: relationshipPatternMatches,
    asset_mobility_matches: assetMobilityMatches,
    environment_pattern_matches: environmentPatternMatches,
    life_timeline_matches: lifeTimelineMatches,
    value_system_matches: valueSystemMatches,
    decision_style_matches: decisionStyleMatches,
    social_capital_matches: socialCapitalMatches,
    energy_depletion_matches: energyDepletionMatches,
    intimacy_family_path_matches: intimacyFamilyPathMatches,
    wealth_path_matches: wealthPathMatches,
    money_personality_matches: moneyPersonalityMatches,
    saving_behavior_matches: savingBehaviorMatches,
    health_financial_matches: healthFinancialMatches,
    family_finance_matches: familyFinanceMatches,
    income_path_matches: incomePathMatches,
    macro_era_matches: macroEraMatches,
    turning_points: turningPoints,
    branch_weights: branchWeights,
    life_evolution: lifeEvolution,
    deep_simulation: deepSimulation,
    llm_simulation_cost: llmSimulationCost,
    llm_reaction_plan: llmReactionPlan,
    calibration,
    confidence_explanation: confidenceExplanation,
    review_path: reviewPath,
    world,
    world_forces: worldForces,
    branches
  };
}

module.exports = {
  synthesizeReport
};
